[package]
name = "hippo-voip"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
base64 = "0.22"
amuse = { workspace = true }
thiserror = "2.0.11"

[lints]
workspace = true
